"""
Smoke test for Phase 0 Git Integration.

Tests:
1. Backend authentication
2. File commit to git-service-smoke branch
3. repository_dispatch webhook trigger
4. Session metadata in payload

Usage:
    # Start backend first:
    python backend/main.py

    # Then run test:
    python tests/smoke_test_git_service.py
"""

import os
import sys
import requests
import json
from pathlib import Path
from dotenv import load_dotenv

# Load environment
load_dotenv()

# Configuration
API_URL = os.getenv("AGENCY_API_URL", "http://localhost:8000")
TEST_BRANCH = "main"  # Using main branch for smoke test
TEST_SESSION = "Puck_Components"
TEST_PROJECT = "IDSE_Core"

# Test artifact content
TEST_SPEC_CONTENT = """# Puck Components Specification (SMOKE TEST)

## Overview
This is a smoke test artifact for Phase 0 Git Integration.

## Purpose
Verify that:
1. Git service can commit to GitHub
2. Session metadata is preserved
3. repository_dispatch webhook is triggered
4. File paths use session-scoped structure

## Session Info
- Project: IDSE_Core
- Session: Puck_Components
- Branch: git-service-smoke

## Generated By
IDSE Agency - Phase 0 Smoke Test

---
This file was generated to test the git integration layer.
It can be safely deleted after testing.
"""


def test_health():
    """Test 1: Verify backend is running."""
    print("\n🧪 Test 1: Backend Health Check")
    try:
        response = requests.get(f"{API_URL}/health", timeout=5)
        if response.status_code == 200:
            data = response.json()
            print(f"   ✅ Backend online: {data.get('service')}")
            return True
        else:
            print(f"   ❌ Backend returned {response.status_code}")
            return False
    except requests.exceptions.ConnectionError:
        print(f"   ❌ Cannot connect to backend at {API_URL}")
        print(f"   💡 Start backend with: python backend/main.py")
        return False


def test_git_auth():
    """Test 2: Verify GitHub authentication."""
    print("\n🧪 Test 2: GitHub Authentication")
    try:
        response = requests.get(f"{API_URL}/api/git/status", timeout=5)
        if response.status_code == 200:
            data = response.json()
            if data.get("success"):
                print(f"   ✅ Authenticated as: {data.get('authenticated_user')}")
                print(f"   ✅ Repository: {data.get('repo')}")
                print(f"   ✅ Write access: {data.get('has_write_access')}")
                return True
            else:
                print(f"   ❌ Authentication failed: {data.get('error')}")
                return False
        else:
            error = response.json().get("detail", "Unknown error")
            print(f"   ❌ Status check failed: {error}")
            return False
    except Exception as e:
        print(f"   ❌ Error: {e}")
        return False


def test_commit_artifact():
    """Test 3: Commit test artifact to git-service-smoke branch."""
    print("\n🧪 Test 3: Commit Artifact")

    # Prepare test file
    test_file_path = "tests/smoke_test_artifact.md"

    payload = {
        "session_id": TEST_SESSION,
        "project": TEST_PROJECT,
        "files": [
            {
                "path": test_file_path,
                "content": TEST_SPEC_CONTENT
            }
        ],
        "message": "test: smoke test for git service integration",
        "branch": TEST_BRANCH,
        "trigger_dispatch": True
    }

    try:
        response = requests.post(
            f"{API_URL}/api/git/commit",
            json=payload,
            timeout=30
        )

        if response.status_code == 200:
            data = response.json()
            if data.get("success"):
                print(f"   ✅ Committed successfully")
                print(f"      Commit SHA: {data.get('commit_sha')[:7]}")
                print(f"      Branch: {data.get('branch')}")
                print(f"      Files: {data.get('files_committed')}")
                print(f"      URL: {data.get('commit_url')}")

                # Check dispatch
                dispatch = data.get("dispatch", {})
                if dispatch.get("success"):
                    print(f"   ✅ repository_dispatch triggered")
                    print(f"      Event: {dispatch.get('event_type')}")
                    print(f"      Payload: {json.dumps(dispatch.get('payload'), indent=8)}")
                    return True
                else:
                    print(f"   ⚠️  Dispatch failed: {dispatch.get('error')}")
                    return True  # Commit succeeded even if dispatch failed
            else:
                print(f"   ❌ Commit failed: {data.get('error')}")
                return False
        else:
            error = response.json().get("detail", "Unknown error")
            print(f"   ❌ Commit request failed: {error}")
            return False

    except Exception as e:
        print(f"   ❌ Error: {e}")
        return False


def run_smoke_tests():
    """Run all smoke tests."""
    print("=" * 60)
    print("Phase 0 Git Integration - Smoke Test")
    print("=" * 60)

    # Check environment
    if not os.getenv("GITHUB_PAT"):
        print("\n❌ GITHUB_PAT not set in .env file")
        print("💡 Add your GitHub Personal Access Token to .env:")
        print("   GITHUB_PAT=ghp_your_token_here")
        return False

    # Run tests
    results = []
    results.append(("Backend Health", test_health()))
    results.append(("GitHub Auth", test_git_auth()))
    results.append(("Commit Artifact", test_commit_artifact()))

    # Summary
    print("\n" + "=" * 60)
    print("Test Summary")
    print("=" * 60)

    passed = sum(1 for _, result in results if result)
    total = len(results)

    for test_name, result in results:
        status = "✅ PASS" if result else "❌ FAIL"
        print(f"{status}  {test_name}")

    print(f"\nResults: {passed}/{total} tests passed")

    if passed == total:
        print("\n🎉 All smoke tests passed!")
        print(f"\n💡 Next steps:")
        print(f"   1. Check commit on GitHub: https://github.com/{os.getenv('GITHUB_OWNER')}/{os.getenv('GITHUB_REPO')}/tree/{TEST_BRANCH}")
        print(f"   2. Verify repository_dispatch triggered (check Actions tab)")
        print(f"   3. Wire CommitArtifactsTool into agent workflows")
        return True
    else:
        print("\n⚠️  Some tests failed. Check logs above.")
        return False


if __name__ == "__main__":
    success = run_smoke_tests()
    sys.exit(0 if success else 1)
