#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/bootstrap_idse_session.sh <PROJECT_NAME> <SESSION_NAME>

Scaffolds a new IDSE project session from templates, repoints the "current"
artifacts to that session, runs governance validators, and updates the session
REPORTS_INDEX.json.

Examples:
  scripts/bootstrap_idse_session.sh Project_Status_Browser session-1765832163

Notes:
- Uses templates from docs/kb/templates/*.md.
- Creates/keeps files if they already exist (will not overwrite session files).
- Symlinks intents/contexts/specs/plans/tasks/feedback/implementation under
  the "current" paths to the new session.
- Runs:
    python3 idse-governance/validate-artifacts.py --project <PROJECT> --session <SESSION> --report-dir reports/projects/<PROJECT>/sessions/<SESSION>
    python3 scripts/validate_artifacts.py --session <PROJECT>/<SESSION> --report-dir reports/projects/<PROJECT>/sessions/<SESSION>
EOF
}

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

PROJECT="$1"
SESSION="$2"

TEMPLATES_DIR="docs/kb/templates"

declare -A SESSION_FILES=(
  [intent]="intents/projects/${PROJECT}/sessions/${SESSION}/intent.md"
  [context]="contexts/projects/${PROJECT}/sessions/${SESSION}/context.md"
  [spec]="specs/projects/${PROJECT}/sessions/${SESSION}/spec.md"
  [plan]="plans/projects/${PROJECT}/sessions/${SESSION}/plan.md"
  [test_plan]="plans/projects/${PROJECT}/sessions/${SESSION}/test-plan.md"
  [tasks]="tasks/projects/${PROJECT}/sessions/${SESSION}/tasks.md"
  [feedback]="feedback/projects/${PROJECT}/sessions/${SESSION}/feedback.md"
  [implementation]="implementation/projects/${PROJECT}/sessions/${SESSION}/README.md"
)

copy_if_missing() {
  local src="$1"
  local dest="$2"
  mkdir -p "$(dirname "$dest")"
  if [[ ! -f "$dest" ]]; then
    cp "$src" "$dest"
  fi
}

# 1) Scaffold from templates (no overwrite for existing session files)
copy_if_missing "${TEMPLATES_DIR}/intent-template.md" "${SESSION_FILES[intent]}"
copy_if_missing "${TEMPLATES_DIR}/context-template.md" "${SESSION_FILES[context]}"
copy_if_missing "${TEMPLATES_DIR}/spec-template.md" "${SESSION_FILES[spec]}"
copy_if_missing "${TEMPLATES_DIR}/plan-template.md" "${SESSION_FILES[plan]}"
copy_if_missing "${TEMPLATES_DIR}/test-plan-template.md" "${SESSION_FILES[test_plan]}"
copy_if_missing "${TEMPLATES_DIR}/tasks-template.md" "${SESSION_FILES[tasks]}"
copy_if_missing "${TEMPLATES_DIR}/feedback-template.md" "${SESSION_FILES[feedback]}"

# Implementation scaffold: create a minimal pointer if missing
if [[ ! -f "${SESSION_FILES[implementation]}" ]]; then
  mkdir -p "$(dirname "${SESSION_FILES[implementation]}")"
  cat > "${SESSION_FILES[implementation]}" <<EOF
# Implementation Scaffold – ${PROJECT}

This session README tracks implementation notes for ${PROJECT}/${SESSION}.
EOF
fi

# 2) Repoint "current" artifacts via symlinks to the new session
declare -A CURRENT_LINKS=(
  [intent]="intents/current/intent.md"
  [context]="contexts/current/context.md"
  [spec]="specs/current/spec.md"
  [plan]="plans/current/plan.md"
  [test_plan]="plans/current/test-plan.md"
  [tasks]="tasks/current/tasks.md"
  [feedback]="feedback/current/feedback.md"
  [implementation]="implementation/current/README.md"
)

for key in "${!CURRENT_LINKS[@]}"; do
  dest="${CURRENT_LINKS[$key]}"
  target="../projects/${PROJECT}/sessions/${SESSION}/$(basename "${SESSION_FILES[$key]}")"
  mkdir -p "$(dirname "$dest")"
  ln -sf "$target" "$dest"
done

# 3) Run validators
REPORT_DIR="reports/projects/${PROJECT}/sessions/${SESSION}"
mkdir -p "$REPORT_DIR"

python3 idse-governance/validate-artifacts.py \
  --project "$PROJECT" \
  --session "$SESSION" \
  --report-dir "$REPORT_DIR"

python3 scripts/validate_artifacts.py \
  --session "${PROJECT}/${SESSION}" \
  --report-dir "$REPORT_DIR" \
  > "${REPORT_DIR}/scripts-validate.log" || true

# 4) Update REPORTS_INDEX.json for this session
VALIDATE_REPORT_PATH="${REPORT_DIR}/validate-artifacts-report.txt"
SCRIPTS_VALIDATE_PATH="${REPORT_DIR}/scripts-validate.log"

TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "implementation/projects/${PROJECT}/sessions/${SESSION}/REPORTS_INDEX.json" <<EOF
{
  "project": "${PROJECT}",
  "session": "${SESSION}",
  "last_updated": "${TIMESTAMP}",
  "status": "OPEN",
  "reports": {
    "governance_summary": null,
    "validate_artifacts": "$( [[ -f "${VALIDATE_REPORT_PATH}" ]] && echo "${VALIDATE_REPORT_PATH}" || echo null )",
    "check_compliance": null,
    "audit_feedback": null,
    "scripts_validate": "$( [[ -f "${SCRIPTS_VALIDATE_PATH}" ]] && echo "${SCRIPTS_VALIDATE_PATH}" || echo null )"
  },
  "notes": "Auto-generated by bootstrap_idse_session.sh"
}
EOF

echo "✅ Bootstrapped ${PROJECT}/${SESSION}"
echo "Reports: ${VALIDATE_REPORT_PATH} (if present), ${SCRIPTS_VALIDATE_PATH}"
